### ISSUE TITLE
parallel deployments

### ISSUE THREAD

**Issue by rawdaGastan** [codescalers/cloud4students#112]
- we need to test parallel deployments

**Comment by xmonader** [comment]
it seems to be failing atm, there could be multiple options
1- create an account for every new user and we do transfer with the quota amount that we allow
2- we queue up deployment requests and notify the user when their deployment is ready via email
3- ?

**Comment by xmonader** [comment]
Seems the most viable solution now, is queuing up the deployment requests and every 5 seconds we collect and do a batch call to deploy, it will still be reasonably fast, and the response will be synchoronus to the user. The main concern is what to do in case of failures in on of the batched calls.

Implementation details: probably should use redis streams, otherwise we will be manually handling too much for no reason

**Comment by rawdaGastan** [comment]
wait for: 
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/116
- https://github.com/threefoldtech/tfchain/issues/687
